name: Deploy Next.js site to Pages

on:
  push:
    branches: ["test/v1.0.0"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "command=install" >> $GITHUB_OUTPUT
            echo "runner=yarn" >> $GITHUB_OUTPUT
            exit 0
          elif [ -f "${{ github.workspace }}/package.json" ]; then
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "command=ci" >> $GITHUB_OUTPUT
            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: ${{ steps.detect-package-manager.outputs.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            host-app/.next
            remote-app/.next
            remote-next/.next
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-

      # Host-app içinde npm install ve build
      - name: Install dependencies for host-app
        run: cd host-app && ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build host-app
        run: cd host-app && ${{ steps.detect-package-manager.outputs.runner }} next build -o out

      # Remote-app içinde npm install ve build
      - name: Install dependencies for remote-app
        run: cd remote-app && ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build remote-app
        run: cd remote-app && ${{ steps.detect-package-manager.outputs.runner }} next build -o out

      # Remote-next içinde npm install ve build
      - name: Install dependencies for remote-next
        run: cd remote-next && ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}

      - name: Build remote-next
        run: cd remote-next && ${{ steps.detect-package-manager.outputs.runner }} next build -o out

      # Tüm build dosyalarını tek bir klasöre kopyala
      - name: Merge all build outputs
        run: |
          mkdir -p final_output
          cp -r host/out final_output/host
          cp -r host-app/out final_output/host-app
          cp -r remote-app/out final_output/remote-app
          cp -r remote-next/out final_output/remote-next

      # Start projects in parallel using pnpm
      - name: Start all services in parallel
        run: |
          echo "Starting all services in parallel..."
          nohup pnpm --parallel --filter nextjs-react_* run dev > services.log 2>&1 &

      # Build edilen dosyaları yükleme
      - name: Upload all artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: final_output

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
